stages:
  preprocess:
    cmd: python src/data_preprocessing.py
    deps:
      - src/data_preprocessing.py
      - data/raw
      - params.yaml
    params:
      - data.image_size
      - data.train_ratio
      - data.val_ratio
      - data.random_seed
    outs:
      - data/splits

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - src/model.py
      - data/splits
      - params.yaml
    params:
      - model
      - augmentation
      - data.batch_size
    outs:
      - models/best_model.pt
    plots:
      - artifacts/loss_curves.png
      - artifacts/accuracy_curves.png
      - artifacts/confusion_matrix.png
    metrics:
      - artifacts/classification_report.txt:
          cache: false
